###register
POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
  "username":"ali",
  "email":"ali@yahoo.com",
  "password":"123456"
}

###login
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "email":"ali@yahoo.com",
  "password":"123456"
}

###logout
POST http://127.0.0.1:3000/auth/logout